# Generated by Django 3.2 on 2021-10-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_authuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='fisrt name'),
        ),
        migrations.AlterField(
            model_name='authuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='last name'),
        ),
    ]
