# Generated by Django 3.2 on 2021-10-18 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211018_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='additional_data', serialize=False, to='accounts.authuser')),
                ('date_birth', models.DateField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
    ]
